### ISSUE TITLE
Bounty System

### ISSUE THREAD

**Issue by bifrostyyy** [VeriFi-World/VeriFi#16]
## Overview

Create system where users can place a "bounty" on an establishment that provides extra incentives for contributors and validators to add that AP to the VeriNet.

## Design

- [ ] Users limited to 10 bounties
- [ ] Multiple bounties can be placed on the same establishment / AP (increasing # of VeriPoints earned by Contributor)
- [ ] Bounties cannot be placed on VeriFied APs
- [ ] Bounties can be placed on UnVeriFied APs

### Firestore / Backend

- [ ] Create new bounty collection in Firestore
- [ ] Create example bounties in Firebase emulator setup
- [ ] Document bounty document schema
- [ ] Update AP schema with bounties
- [ ] Add Profile schema with bounties
- [ ] Write Cloud Function that adds additional VeriPoints to user profile if validation / contribution event is tied to a bounty

### Repositories

- [ ] Add business logic for user to add bounty to Bounty Firestore collection
    - [ ] Ensure bounty is also stored in Profile bounty tracker
    - [ ] Ensure bounty tracker length never exceeds 10 per user
- [ ] Add business l

### VeriMap

- [ ]  Add new AP marker icon that is used when UnVeriFied AP has a bounty
- [ ]  Add new marker icon that is used when an establishment w/ unknown AP has a bounty
- [ ]  Implement card / bottom sheet that shows bounty information for unknown AP
- [ ]  Add to UnVeriFied AP details card / bottom sheet to show bounty information

## Tasks

- [ ] VeriFi-World/VeriFi#12
- [ ] VeriFi-World/VeriFi#13
- [ ] VeriFi-World/VeriFi#14
- [ ] VeriFi-World/VeriFi#15
- [ ] Add Nearby Bounties tab to Achievements page
- [ ] Create new marker icons for UnVeriFied APs w/ a bounty and Unknown APs w/ bounty
- [ ] Create a new button + controller on map for adding a new Bounty to the map
- [ ] Create AddBountyDialog that overlays map for adding a new Bounty to the map
- [ ] Add button to AccessPointInfoSheet for adding a Bounty to that AP
