### ISSUE TITLE
Continuous Integration Pipelines

### ISSUE THREAD

**Issue by bifrostyyy** [VeriFi-World/VeriFi#7]
In order to quickly triage bugs, release new features, etc., we need to leverage GitHub Actions to test, build, and deploy new releases of our app and plugins

### VeriFi App

- Create a GitHub Actions pipeline that runs QA/QC jobs (testing, linting, etc.) for every commit / PR to`main`.
    - Jobs should be nearly identical to what the developer should be running locally on their machine.
- Have every commit to `main` trigger a new release to Firebase App Distribution. This should increment the build number, but not the version number.
- Have a separate release pipeline that is triggered manually to publish a new release to the Google + Apple app stores. This pipeline should enforce a "release checklist" that the release engineer should follow. It ensures that the changelog has been updated, new screenshots generated, etc.
    - This pipeline should be run on at least a weekly basis. More to follow on how VeriFi will do semantic versioning.

### Auto Connect Plugin

- Create a GitHub Actions pipeline that runs QA/QC jobs (testing, linting, etc.) for every commit / PR to`main`.
   - Jobs should be nearly identical to what the developer should be running locally on their machine.
- Every PR should result in version increment.
- Ensure pipeline also enforces checklist (manual or automated) for pub.dev

## Tasks

- [ ] Create development pipeline for main branch
- [ ] Create Firebase App Distribution workflow for continuous integration builds
- [ ] Create release pipeline for production deployments
- [ ] Create release checklist
